config/routes.rb
Kickball::Application.routes.draw do
  resources :games

  

end

app/models/game.rb
class Game < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render action: 'show', status: :created, location: @game }
      else
        format.html { render action: 'new' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:team_1_name, :team_2_name, :team_1_score, :team_2_score, :team_1_captain, :team_2_captain, :played_on)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :team_1_name %><br>
    <%= f.text_field :team_1_name %>
  </div>
  <div class="field">
    <%= f.label :team_2_name %><br>
    <%= f.text_field :team_2_name %>
  </div>
  <div class="field">
    <%= f.label :team_1_score %><br>
    <%= f.number_field :team_1_score %>
  </div>
  <div class="field">
    <%= f.label :team_2_score %><br>
    <%= f.number_field :team_2_score %>
  </div>
  <div class="field">
    <%= f.label :team_1_captain %><br>
    <%= f.text_field :team_1_captain %>
  </div>
  <div class="field">
    <%= f.label :team_2_captain %><br>
    <%= f.text_field :team_2_captain %>
  </div>
  <div class="field">
    <%= f.label :played_on %><br>
    <%= f.date_select :played_on %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Listing games</h1>

<table>
  <thead>
    <tr>
      <th>Team 1 name</th>
      <th>Team 2 name</th>
      <th>Team 1 score</th>
      <th>Team 2 score</th>
      <th>Team 1 captain</th>
      <th>Team 2 captain</th>
      <th>Played on</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.team_1_name %></td>
        <td><%= game.team_2_name %></td>
        <td><%= game.team_1_score %></td>
        <td><%= game.team_2_score %></td>
        <td><%= game.team_1_captain %></td>
        <td><%= game.team_2_captain %></td>
        <td><%= game.played_on %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Team 1 name:</strong>
  <%= @game.team_1_name %>
</p>

<p>
  <strong>Team 2 name:</strong>
  <%= @game.team_2_name %>
</p>

<p>
  <strong>Team 1 score:</strong>
  <%= @game.team_1_score %>
</p>

<p>
  <strong>Team 2 score:</strong>
  <%= @game.team_2_score %>
</p>

<p>
  <strong>Team 1 captain:</strong>
  <%= @game.team_1_captain %>
</p>

<p>
  <strong>Team 2 captain:</strong>
  <%= @game.team_2_captain %>
</p>

<p>
  <strong>Played on:</strong>
  <%= @game.played_on %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kickball</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>